# Generated by Django 4.1.7 on 2023-03-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiny',
            new_name='quantity',
        ),
    ]
